# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(857, 391)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setMinimumSize(QtCore.QSize(80, 34))
        self.back_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.back_btn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/back_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon)
        self.back_btn.setIconSize(QtCore.QSize(24, 24))
        self.back_btn.setFlat(True)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        spacerItem = QtWidgets.QSpacerItem(148, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.predict_title = QtWidgets.QLabel(Form)
        self.predict_title.setMinimumSize(QtCore.QSize(211, 60))
        self.predict_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 24pt \"Cairo\";")
        self.predict_title.setAlignment(QtCore.Qt.AlignCenter)
        self.predict_title.setObjectName("predict_title")
        self.horizontalLayout.addWidget(self.predict_title)
        spacerItem1 = QtWidgets.QSpacerItem(278, 58, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BrowseButton_2 = QtWidgets.QPushButton(Form)
        self.BrowseButton_2.setMinimumSize(QtCore.QSize(131, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseButton_2.setFont(font)
        self.BrowseButton_2.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.BrowseButton_2.setIconSize(QtCore.QSize(70, 70))
        self.BrowseButton_2.setObjectName("BrowseButton_2")
        self.horizontalLayout_2.addWidget(self.BrowseButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.BrowseButton_3 = QtWidgets.QPushButton(Form)
        self.BrowseButton_3.setMinimumSize(QtCore.QSize(271, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseButton_3.setFont(font)
        self.BrowseButton_3.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.BrowseButton_3.setIconSize(QtCore.QSize(70, 70))
        self.BrowseButton_3.setObjectName("BrowseButton_3")
        self.horizontalLayout_2.addWidget(self.BrowseButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.BrowseButton_4 = QtWidgets.QPushButton(Form)
        self.BrowseButton_4.setMinimumSize(QtCore.QSize(135, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseButton_4.setFont(font)
        self.BrowseButton_4.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.BrowseButton_4.setIconSize(QtCore.QSize(70, 70))
        self.BrowseButton_4.setObjectName("BrowseButton_4")
        self.horizontalLayout_2.addWidget(self.BrowseButton_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 147, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "HTI Table Generator "))
        self.back_btn.setText(_translate("Form", " back "))
        self.predict_title.setText(_translate("Form", "Table Generator"))
        self.BrowseButton_2.setText(_translate("Form", "Computer Science"))
        self.BrowseButton_3.setText(_translate("Form", " custome table"))
        self.BrowseButton_4.setText(_translate("Form", "Upload DB"))
import app_resources_rc
